PetikoyVeterinary/Components/AdminSideBarMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace PetikoyVeterinaryUI.Components
{
    public class AdminSideBarMenuViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {

            return View();

        }
    }
}

PetikoyVeterinary/Components/TopBarMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace PetikoyVeterinaryUI.Components
{
    public class TopBarMenuViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

PetikoyVeterinary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetikoyVeterinary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PetikoyVeterinary.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetikoyVeterinary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PetikoyVeterinary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PetikoyVeterinary/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
	<title>PETIKOY CLINIC MANAGEMENT PANEL</title>
	<!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 11]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	<!-- Meta -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="description" content="" />
	<meta name="keywords" content="">
	<meta name="author" content="Phoenixcoded" />
	<!-- Favicon icon -->
	<link rel="icon" href="~/admintheme/assets/images/favicon.ico type="image/x-icon">

	<!-- vendor css -->
	<link rel="stylesheet" href="~/admintheme/assets/css/style.css">



</head>
<body class="">
	<!-- [ Pre-loader ] start -->
	<div class="loader-bg">
		<div class="loader-track">
			<div class="loader-fill"></div>
		</div>
	</div>
	<!-- [ Pre-loader ] End -->
	@await Component.InvokeAsync("AdminSideBarMenu")



	<!-- !!!!!!!!!!!!!-->
	<!-- [ Header ] start  BURAYI KESİP TOPMENU YAPİCAZ AWAIT EKLEYECEZ-->
	@await Component.InvokeAsync("TopBarMenu")
	@* <header class="navbar pcoded-header navbar-expand-lg navbar-light header-dark"> *@
	@* *@
	@* *@
	@* 			<div class="m-header"> *@
	@* 				<a class="mobile-menu" id="mobile-collapse" href="#!"><span></span></a> *@
	@* 				<a href="#!" class="b-brand"> *@
	@* 					<!-- ========   change your logo hear   ============ --> *@
	@* 			<img src="~/admintheme/assets/images/logo.png" alt="" class="logo"> *@
	@* 					<img src="~/admintheme/assets/images/logo-icon.png" alt="" class="logo-thumb"> *@
	@* 				</a> *@
	@* 				<a href="#!" class="mob-toggler"> *@
	@* 					<i class="feather icon-more-vertical"></i> *@
	@* 				</a> *@
	@* 			</div> *@
	@* 			<div class="collapse navbar-collapse"> *@
	@* 				<ul class="navbar-nav mr-auto"> *@
	@* 					<li class="nav-item"> *@
	@* 						<a href="#!" class="pop-search"><i class="feather icon-search"></i></a> *@
	@* 						<div class="search-bar"> *@
	@* 							<input type="text" class="form-control border-0 shadow-none" placeholder="Search hear"> *@
	@* 							<button type="button" class="close" aria-label="Close"> *@
	@* 								<span aria-hidden="true">&times;</span> *@
	@* 							</button> *@
	@* 						</div> *@
	@* 					</li> *@
	@* 					<li class="nav-item"> *@
	@* 						<div class="dropdown"> *@
	@* 							<a class="dropdown-toggle h-drop" href="#" data-toggle="dropdown"> *@
	@* 								Dropdown *@
	@* 							</a> *@
	@* 							<div class="dropdown-menu profile-notification "> *@
	@* 								<ul class="pro-body"> *@
	@* 									<li><a href="user-profile.html" class="dropdown-item"><i class="fas fa-circle"></i> Profile</a></li> *@
	@* 									<li><a href="email_inbox.html" class="dropdown-item"><i class="fas fa-circle"></i> My Messages</a></li> *@
	@* 									<li><a href="auth-signin.html" class="dropdown-item"><i class="fas fa-circle"></i> Lock Screen</a></li> *@
	@* 								</ul> *@
	@* 							</div> *@
	@* 						</div> *@
	@* 					</li> *@
	@* 					<li class="nav-item"> *@
	@* 						<div class="dropdown mega-menu"> *@
	@* 							<a class="dropdown-toggle h-drop" href="#" data-toggle="dropdown"> *@
	@* 								Mega *@
	@* 							</a> *@
	@* 							<div class="dropdown-menu profile-notification "> *@
	@* 								<div class="row no-gutters"> *@
	@* 									<div class="col"> *@
	@* 										<h6 class="mega-title">UI Element</h6> *@
	@* 										<ul class="pro-body"> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="fas fa-circle"></i> Alert</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="fas fa-circle"></i> Button</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="fas fa-circle"></i> Badges</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="fas fa-circle"></i> Cards</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="fas fa-circle"></i> Modal</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="fas fa-circle"></i> Tabs & pills</a></li> *@
	@* 										</ul> *@
	@* 									</div> *@
	@* 									<div class="col"> *@
	@* 										<h6 class="mega-title">Forms</h6> *@
	@* 										<ul class="pro-body"> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-minus"></i> Elements</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-minus"></i> Validation</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-minus"></i> Masking</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-minus"></i> Wizard</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-minus"></i> Picker</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-minus"></i> Select</a></li> *@
	@* 										</ul> *@
	@* 									</div> *@
	@* 									<div class="col"> *@
	@* 										<h6 class="mega-title">Application</h6> *@
	@* 										<ul class="pro-body"> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-mail"></i> Email</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-clipboard"></i> Task</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-check-square"></i> To-Do</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-image"></i> Gallery</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-help-circle"></i> Helpdesk</a></li> *@
	@* 										</ul> *@
	@* 									</div> *@
	@* 									<div class="col"> *@
	@* 										<h6 class="mega-title">Extension</h6> *@
	@* 										<ul class="pro-body"> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-file-plus"></i> Editor</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-file-minus"></i> Invoice</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-calendar"></i> Full calendar</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-upload-cloud"></i> File upload</a></li> *@
	@* 											<li><a href="#!" class="dropdown-item"><i class="feather icon-scissors"></i> Image cropper</a></li> *@
	@* 										</ul> *@
	@* 									</div> *@
	@* 								</div> *@
	@* 							</div> *@
	@* 						</div> *@
	@* 					</li> *@
	@* 				</ul> *@
	@* 				<ul class="navbar-nav ml-auto"> *@
	@* 					<li> *@
	@* 						<div class="dropdown"> *@
	@* 							<a class="dropdown-toggle" href="#" data-toggle="dropdown"> *@
	@* 								<i class="icon feather icon-bell"></i> *@
	@* 								<span class="badge badge-pill badge-danger">5</span> *@
	@* 							</a> *@
	@* 							<div class="dropdown-menu dropdown-menu-right notification"> *@
	@* 								<div class="noti-head"> *@
	@* 									<h6 class="d-inline-block m-b-0">Notifications</h6> *@
	@* 									<div class="float-right"> *@
	@* 										<a href="#!" class="m-r-10">mark as read</a> *@
	@* 										<a href="#!">clear all</a> *@
	@* 									</div> *@
	@* 								</div> *@
	@* 								<ul class="noti-body"> *@
	@* 									<li class="n-title"> *@
	@* 										<p class="m-b-0">NEW</p> *@
	@* 									</li> *@
	@* 									<li class="notification"> *@
	@* 										<div class="media"> *@
	@* 											<img class="img-radius" src="~/admintheme/assets/images/user/avatar-1.jpg" alt="Generic placeholder image"> *@
	@* 											<div class="media-body"> *@
	@* 												<p><strong>John Doe</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>5 min</span></p> *@
	@* 												<p>New ticket Added</p> *@
	@* 											</div> *@
	@* 										</div> *@
	@* 									</li> *@
	@* 									<li class="n-title"> *@
	@* 										<p class="m-b-0">EARLIER</p> *@
	@* 									</li> *@
	@* 									<li class="notification"> *@
	@* 										<div class="media"> *@
	@* 									<img class="img-radius" src="~/admintheme/assets/images/user/avatar-2.jpg" alt="Generic placeholder image"> *@
	@* 											<div class="media-body"> *@
	@* 												<p><strong>Joseph William</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>10 min</span></p> *@
	@* 												<p>Prchace New Theme and make payment</p> *@
	@* 											</div> *@
	@* 										</div> *@
	@* 									</li> *@
	@* 									<li class="notification"> *@
	@* 										<div class="media"> *@
	@* 											<img class="img-radius" src="assets/images/user/avatar-1.jpg" alt="Generic placeholder image"> *@
	@* 											<div class="media-body"> *@
	@* 												<p><strong>Sara Soudein</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>12 min</span></p> *@
	@* 												<p>currently login</p> *@
	@* 											</div> *@
	@* 										</div> *@
	@* 									</li> *@
	@* 									<li class="notification"> *@
	@* 										<div class="media"> *@
	@* 											<img class="img-radius" src="assets/images/user/avatar-2.jpg" alt="Generic placeholder image"> *@
	@* 											<div class="media-body"> *@
	@* 												<p><strong>Joseph William</strong><span class="n-time text-muted"><i class="icon feather icon-clock m-r-10"></i>30 min</span></p> *@
	@* 												<p>Prchace New Theme and make payment</p> *@
	@* 											</div> *@
	@* 										</div> *@
	@* 									</li> *@
	@* 								</ul> *@
	@* 								<div class="noti-footer"> *@
	@* 									<a href="#!">show all</a> *@
	@* 								</div> *@
	@* 							</div> *@
	@* 						</div> *@
	@* 					</li> *@
	@* 					<li> *@
	@* 						<div class="dropdown drp-user"> *@
	@* 							<a href="#" class="dropdown-toggle" data-toggle="dropdown"> *@
	@* 								<i class="feather icon-user"></i> *@
	@* 							</a> *@
	@* 							<div class="dropdown-menu dropdown-menu-right profile-notification"> *@
	@* 								<div class="pro-head"> *@
	@* 									<img src="assets/images/user/avatar-1.jpg" class="img-radius" alt="User-Profile-Image"> *@
	@* 									<span>John Doe</span> *@
	@* 									<a href="auth-signin.html" class="dud-logout" title="Logout"> *@
	@* 										<i class="feather icon-log-out"></i> *@
	@* 									</a> *@
	@* 								</div> *@
	@* 								<ul class="pro-body"> *@
	@* 									<li><a href="user-profile.html" class="dropdown-item"><i class="feather icon-user"></i> Profile</a></li> *@
	@* 									<li><a href="email_inbox.html" class="dropdown-item"><i class="feather icon-mail"></i> My Messages</a></li> *@
	@* 									<li><a href="auth-signin.html" class="dropdown-item"><i class="feather icon-lock"></i> Lock Screen</a></li> *@
	@* 								</ul> *@
	@* 							</div> *@
	@* 						</div> *@
	@* 					</li> *@
	@* 				</ul> *@
	@* 			</div> *@
	@* *@
	@* *@
	@* </header> *@
	<!-- [ Header ] end -->
	<!-- [ Main Content ] start -->
	<div class="pcoded-main-container">
		<div class="pcoded-content">
			<!-- [ breadcrumb ] start -->
			<div class="page-header">
				<div class="page-block">
					<div class="row align-items-center">
						<div class="col-md-12">
							<div class="page-header-title">
								<h5 class="m-b-10">Sample Page</h5>
							</div>
							<ul class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
								<li class="breadcrumb-item"><a href="#!">Sample Page</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!-- [ breadcrumb ] end -->
			<!-- [ Main Content ] start -->
			<div class="row">
				@RenderBody()
				<!-- [ sample-page ] end -->
			</div>
			<!-- [ Main Content ] end -->
		</div>
	</div>
	<!-- [ Main Content ] end -->
	<!-- Warning Section start -->
	<!-- Older IE warning message -->
	<!--[if lt IE 11]>
		<div class="ie-warning">
			<h1>Warning!!</h1>
			<p>You are using an outdated version of Internet Explorer, please upgrade
			   <br/>to any of the following web browsers to access this website.
			</p>
			<div class="iew-container">
				<ul class="iew-download">
					<li>
						<a href="http://www.google.com/chrome/">
							<img src="assets/images/browser/chrome.png" alt="Chrome">
							<div>Chrome</div>
						</a>
					</li>
					<li>
						<a href="https://www.mozilla.org/en-US/firefox/new/">
							<img src="assets/images/browser/firefox.png" alt="Firefox">
							<div>Firefox</div>
						</a>
					</li>
					<li>
						<a href="http://www.opera.com">
							<img src="assets/images/browser/opera.png" alt="Opera">
							<div>Opera</div>
						</a>
					</li>
					<li>
						<a href="https://www.apple.com/safari/">
							<img src="assets/images/browser/safari.png" alt="Safari">
							<div>Safari</div>
						</a>
					</li>
					<li>
						<a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
							<img src="assets/images/browser/ie.png" alt="">
							<div>IE (11 & above)</div>
						</a>
					</li>
				</ul>
			</div>
			<p>Sorry for the inconvenience!</p>
		</div>
	<![endif]-->
	<!-- Warning Section Ends -->
	<!-- Required Js -->
	<script src="~/admintheme/assets/js/vendor-all.min.js"></script>
	<script src="~/admintheme/assets/js/plugins/bootstrap.min.js"></script>
	<script src="~/admintheme/assets/js/pcoded.min.js"></script>
	@await RenderSectionAsync("Scripts", required: false)


</body>

</html>